# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitacaoAlmoxarifado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atendido', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('data_atendimento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAlmoxarifado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=100)),
                ('atendente', models.CharField(blank=True, max_length=100, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField()),
                ('resposta', models.TextField(blank=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'EM ANÁLISE'), (2, 'PARCIALMENTE ATENDIDO'), (3, 'TOTALMENTE ATENDIDO'), (8, 'ARQUIVADA')], default=1)),
                ('data_finalizado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemsolicitacaoalmoxarifado',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitacoes', to='almoxarifado.SolicitacaoAlmoxarifado'),
        ),
    ]
