# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieAlmoxarifado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('estoque_total_cache', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('codigo', 'titulo'),
            },
        ),
        migrations.AddField(
            model_name='itemsolicitacaoalmoxarifado',
            name='unidade_medida',
            field=models.IntegerField(choices=[(10, 'CAIXA'), (9, 'FARDO'), (11, 'GALÃO'), (8, 'KIT'), (7, 'LATA'), (12, 'LITRO'), (6, 'METRO'), (5, 'PACOTE'), (4, 'PAR'), (3, 'PEÇA'), (2, 'ROLO'), (1, 'UNIDADE')], default=1),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaoalmoxarifado',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitacoes_almoxarifado', to='almoxarifado.EspecieAlmoxarifado'),
        ),
    ]
